server:
  port: 8091
 # servlet:
 #  context-path: /api

spring:
  application:
    name: cards-service

  datasource:
    url: jdbc:postgresql://localhost:5432/cards_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog-master.yaml
    default-schema: public

  # Security Configuration
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration

  # Logging Configuration
  logging:
    level:
      com.example.bankcards: DEBUG
      org.springframework.security: DEBUG
      org.springframework.web: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Springdoc OpenAPI Configuration (ВНЕ spring:)
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
  show-login-endpoint: true
  packages-to-scan: com.example.bankcards.controller
  #paths-to-match: /api/**

# JWT Configuration (кастомные свойства)
jwt:
  secret: "U3VwZXJTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb25JbkJhbmtBcHBsaWNhdGlvbjIwMjQ="
  expiration: 900000
  refresh-expiration: 604800000